# Generated by Django 5.1.3 on 2024-11-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0002_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='available_spots',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
    ]
