# Generated by Django 5.1.3 on 2024-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0003_tour_available_spots_tour_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='available_spots',
            new_name='available_bookings',
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
