# Generated by Django 5.1.3 on 2024-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourPackages', '0006_alter_tour_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='def.png', upload_to='images/tour_images/'),
        ),
    ]
