# Generated by Django 5.1.3 on 2024-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
