# Generated by Django 5.1.3 on 2024-11-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='available_rooms',
            new_name='available_bookings',
        ),
    ]
