# Generated by Django 5.1.3 on 2024-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/flight_images/'),
        ),
    ]
