# Generated by Django 5.1.3 on 2024-11-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, default='default_flight.png', null=True, upload_to='images/flight_images/'),
        ),
    ]
